export const digitalAssets = [
    {
        assetId: 1,
        title: 'IPM-2024-0892 고효율 영구자석 동기전동기 설계 도면',
        assetType: '설계도면',
        motorType: 'IPMSM',
        description: '고효율 IPMSM 모터의 상세 설계 도면입니다. 냉각 구조 및 자석 배치 포함.',
        registrant: '김철수',
        registrantEmail: 'cs.kim@clew.tech',
        registeredDate: '2024-01-10',
        updatedDate: '2024-01-15',
        fileSize: '24.5 MB',
        fileType: 'DWG',
        version: '1.2',
        status: 'active', // active, archived, draft
    },
    {
        assetId: 2,
        title: 'BMS-2024-0156 배터리 관리 시스템 사양서',
        assetType: '사양서',
        motorType: 'SPMSM',
        description: 'BMS 시스템의 전체 사양서입니다. 통신 프로토콜 및 안전 기준 포함.',
        registrant: '이민수',
        registrantEmail: 'ms.lee@clew.tech',
        registeredDate: '2024-01-08',
        updatedDate: '2024-01-08',
        fileSize: '8.2 MB',
        fileType: 'PDF',
        version: '1.0',
        status: 'active',
    },
    {
        assetId: 3,
        title: 'INV-2024-0234 인버터 회로도',
        assetType: '회로도',
        motorType: 'IM',
        description: '3상 인버터 회로도입니다. 전력부 및 게이트 드라이버 회로 포함.',
        registrant: '박영희',
        registrantEmail: 'yh.park@clew.tech',
        registeredDate: '2024-01-05',
        updatedDate: '2024-01-12',
        fileSize: '15.8 MB',
        fileType: 'SCH',
        version: '2.1',
        status: 'active',
    },
    {
        assetId: 4,
        title: 'MCU-2024-0567 제어기 펌웨어 문서',
        assetType: '기술문서',
        motorType: 'BLDC',
        description: 'MCU 펌웨어 아키텍처 및 API 문서입니다.',
        registrant: '최지훈',
        registrantEmail: 'jh.choi@clew.tech',
        registeredDate: '2024-01-03',
        updatedDate: '2024-01-03',
        fileSize: '5.4 MB',
        fileType: 'PDF',
        version: '1.0',
        status: 'active',
    },
    {
        assetId: 5,
        title: 'SEN-2024-0891 센서 인터페이스 규격서',
        assetType: '규격서',
        motorType: 'SRM',
        description: '센서 모듈 인터페이스 규격서입니다. CAN 통신 프로토콜 포함.',
        registrant: '한소영',
        registrantEmail: 'sy.han@clew.tech',
        registeredDate: '2024-01-01',
        updatedDate: '2024-01-10',
        fileSize: '3.2 MB',
        fileType: 'PDF',
        version: '1.1',
        status: 'active',
    },
];

// 2. 요청 목록 (assetId로 연결)
export const assetRequests = [
    {
        requestId: 1,
        assetId: 1, // IPM-2024-0892 연결
        requestDate: '2024-01-15',
        requester: '정다운',
        requesterEmail: 'dw.jung@motorspace.io',
        requesterTeam: 'Motorspace',
        requestDescription: '신규 전기차 프로젝트에 적용할 IPM 모터 설계 검토를 위해 해당 도면이 필요합니다.',
        status: 'approved',
        approver: '박영희',
        approverEmail: 'yh.park@clew.tech',
        processedDate: '2024-01-16',
        processDescription: '프로젝트 목적 확인 완료. 외부 유출 금지 조건 부여.',
    },
    {
        requestId: 2,
        assetId: 1, // 같은 자료에 다른 요청
        requestDate: '2024-01-18',
        requester: '김태호',
        requesterEmail: 'th.kim@geneers.com',
        requesterTeam: 'GENEERS',
        requestDescription: '모터 효율 분석을 위해 설계 도면 검토가 필요합니다.',
        status: 'pending',
        approver: null,
        approverEmail: null,
        processedDate: null,
        processDescription: null,
    },
    {
        requestId: 3,
        assetId: 2, // BMS 사양서
        requestDate: '2024-01-14',
        requester: '이민수',
        requesterEmail: 'ms.lee@clew.tech',
        requesterTeam: 'CLEW',
        requestDescription: 'BMS 시스템 통합 테스트를 위해 상세 사양서가 필요합니다.',
        status: 'approved',
        approver: '박영희',
        approverEmail: 'yh.park@clew.tech',
        processedDate: '2024-01-15',
        processDescription: '내부 프로젝트 용도로 승인합니다.',
    },
    {
        requestId: 4,
        assetId: 3, // 인버터 회로도
        requestDate: '2024-01-13',
        requester: '정다운',
        requesterEmail: 'dw.jung@motorspace.io',
        requesterTeam: 'Motorspace',
        requestDescription: '인버터 고장 분석을 위해 회로도 검토가 필요합니다.',
        status: 'pending',
        approver: null,
        approverEmail: null,
        processedDate: null,
        processDescription: null,
    },
    {
        requestId: 5,
        assetId: 4, // MCU 펌웨어
        requestDate: '2024-01-12',
        requester: '최지훈',
        requesterEmail: 'jh.choi@geneers.com',
        requesterTeam: 'GENEERS',
        requestDescription: '펌웨어 커스터마이징을 위해 소스코드 및 문서가 필요합니다.',
        status: 'rejected',
        approver: '김대표',
        approverEmail: 'ceo@clew.tech',
        processedDate: '2024-01-13',
        processDescription: '해당 자료는 핵심 기술 자산으로 분류되어 외부 공유가 불가합니다.',
    },
];